"""Rename fields in ExampleModel2

Revision ID: 32333b83d6a0
Revises: e7ba4c95ef74
Create Date: 2024-11-22 08:43:28.568932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32333b83d6a0'
down_revision: Union[str, None] = 'e7ba4c95ef74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('modifiedAt', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam', 'modifiedAt')
    # ### end Alembic commands ###
