"""Rename fields in ExampleModel

Revision ID: e7ba4c95ef74
Revises: 
Create Date: 2024-11-22 08:42:58.211558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7ba4c95ef74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam', 'modifiedAtt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('modifiedAtt', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
